### ISSUE TITLE
Some data cannot be obtained when event_type is app_mentioned

### ISSUE THREAD

**Issue by tsukaby** [slack-samples/deno-code-snippets#9]
Hello.
I am currently using app_mentioned, but there is something I am not sure about.

```
const trigger: Trigger<typeof MyWorkflow.definition> = {
  ...
  event: {
    event_type: "slack#/events/app_mentioned",
...
```

The following documentation appears to include message_ts in the app_mentioned event, but I can't actually get them.
https://api.slack.com/automation/triggers/event
```
{
  "team_id": "T0123ABC",
  "enterprise_id": "E0123ABC",
  "event_id": "Ev0123ABC",
  "event_timestamp": 1643810217.088700,
  "type": "event",
  "data": {
    "app_id": "A1234ABC",
    "channel_id": "C0123ABC",
    "channel_name": "cool-channel",
    "channel_type": "public/private/im/mpim",
    "event_type": "slack#/events/app_mentioned",
    "message_ts": "164432432542.2353",
    "text": "<@U0LAN0Z89> is it everything a river should be?",
    "user_id:": "U0123ABC",
  }
}
```

The input definition on my workflow side exists, but when I actually debug it, it is empty.
Is this a known issue?

I can provide a sample repository and PR if needed.
Thanks 😄

**Comment by seratch** [comment]
Hey @tsukaby, thanks for writing in!

A possible cause of your situation that I can think of is that you may create the trigger without message_ts first and then added the property in the definition. If you haven't re-created the trigger, your change to the trigger definition is not reflected to the Slack server-side. To resolve this, you can run `slack trigger delete` and then `slack trigger create` commands with the updated definition.

Since we are now chatting about this in Japanese on Twitter, let me close this issue now.
